version: '3.8'

services:

  zentao-db:
    image: bitnami/mariadb:10.6
    container_name: zentao-db
    restart: always
    volumes:
      - ./mariadb:/bitnami/mariadb
    networks:
      - zentao-net
    environment:
      - MARIADB_ROOT_PASSWORD=pass4Zentao
      - MARIADB_DATABASE=zentao
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  zentao-cache:
    image: bitnami/redis:6.2
    container_name: zentao-cache
    restart: always
    environment:
      - REDIS_PASSWORD=pass4Zentao
    volumes:
      - ./redis:/bitnami/redis/data
    networks:
      - zentao-net

  zentao:
    image: easysoft/zentao:latest
    container_name: zentao
    restart: always
    ports:
      - '9527:80'
    volumes:
      - ./zentao:/data
      - ./zentao/sess:/tmp/sess
    depends_on:
      - zentao-db
      - zentao-cache
    environment:
      - ZT_MYSQL_HOST=zentao-db
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=my_user
      - ZT_MYSQL_PASSWORD=my_password
      - ZT_MYSQL_DB=zentao

      - ZT_REDIS_HOST=zentao-cache
      - ZT_REDIS_PORT=6379
      - ZT_REDIS_PASSWORD=pass4Zentao
      - ZT_REDIS_SERIALIZER=igbinary
      - ZT_CACHE_ENABLE=true
      - ZT_CACHE_TYPE=redis
      - ZT_CACHE_SCOPE=private
      - ZT_CACHE_LIFETIME=0

      - PHP_SESSION_TYPE=redis
      - PHP_SESSION_PATH=tcp://zentao-cache:6379?auth=pass4Zentao
      - PHP_EXT_REDIS=true
      - PHP_SESSION_REDIS_DATABASE=6

      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M

    networks:
      - zentao-net

networks:
  zentao-net:
    driver: bridge

